### ISSUE TITLE
 Failed to load Huggingface native library for cudart64_65.dll

### ISSUE THREAD

**Issue by imbaTapac** [deepjavalibrary/djl#2709]
## Description
Error **java.lang.StringIndexOutOfBoundsException: begin 2, end 5, length 4** while starting HuggingFaceTokenizer
When starting HuggingFaceTokenizer from **HuggingFaceTokenizer.newInstance(Paths.get("tokenizer.json"))**

### Expected Behavior
Successfully loaded tokenizer

### Error Message
```
DEBUG ai.djl.util.cuda.CudaUtils - Found cudart: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
Exception in thread "main" ai.djl.engine.EngineException: Failed to load Huggingface native library.
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:43)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:146)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:132)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:115)
	at Application.main(Application.java:43)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 2, end 5, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at ai.djl.util.Platform.matches(Platform.java:300)
	at ai.djl.util.Platform.detectPlatform(Platform.java:81)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:76)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:66)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	... 4 more
Disconnected from the target VM, address: '127.0.0.1:52857', transport: 'socket'

Process finished with exit code 1
```

## How to Reproduce?
When starting HuggingFaceTokenizer from **HuggingFaceTokenizer.newInstance** no matters with each params
With cuda `ai.djl.util.cuda.CudaUtils - Found cudart: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll`

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.Using **ai.djl.huggingface** lib version 0.22.1
2. String application with line **HuggingFaceTokenizer.newInstance** no matters with each params

## What have you tried to solve it?

1. Dont understand even why it doesnt work and why in code there is hardcoded **flavor.substring(2, 5)**

**Comment by frankfliu** [comment]
This is a duplicate of #2581 and should have been fixed in 0.23.0

**Comment by imbaTapac** [comment]
Got you, thanks.
BTW
How to understand which tools need be installed before running tokeniser on Windows x64?
I downloaded CUDA toolkit 12.0 but it didnt help. 
Is there any FAQ how do the properly upgrade of CUDA?

**Comment by frankfliu** [comment]
You don't need cuda for tokenizer. CUDA is only used for PyTorch/TensorFlow/MXNet/Onnx etc.

In order for DJL to pickup and correct CUDA version, you need to set PATH env to make sure the desired version of `cudart64_*.dll` can be found first. You can also set `CUDA_PATH` for windows.

**Comment by imbaTapac** [comment]
Thanks, it helped!
