### ISSUE TITLE
Pytorch Error On ModelLoading

### ISSUE THREAD

**Issue by nikkisingh111333** [deepjavalibrary/djl#900]
hey i cannot get over from pytorch error i m struggling from 2 days.. heres what i want MY CODE below:

**GETTING CUDA 10.2 READY**

```
`!curl -O https://raw.githubusercontent.com/aws-samples/d2l-java/master/tools/colab_build.sh && bash colab_build.sh
!sudo rm /usr/local/cuda
!ln -s /usr/local/cuda-10.2 /usr/local/cuda
!ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib64-nvidia
!nvcc --version
!python3 install.py --sys-prefix
!pip install pyngrok --quiet`
```

**IMPORTING PAKAGES**

```
%maven ai.djl:api:0.10.0
%maven ai.djl:model-zoo:0.10.0
%maven ai.djl:examples:0.6.0
%maven ai.djl.pytorch:pytorch-model-zoo:0.10.0
%maven ai.djl.pytorch:pytorch-engine:0.10.0
%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:2.0.0-alpha1
%maven net.java.dev.jna:jna:5.3.0
%maven ai.djl:basicdataset:0.10.0
// for more PyTorch library selection options
%maven ai.djl.pytorch:pytorch-native-auto:1.8.1
```

```
import ai.djl.ModelException;
import ai.djl.engine.Engine;
import ai.djl.inference.Predictor;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ModelZoo;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.TranslateException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.output.BoundingBox;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.output.*;
import ai.djl.modality.cv.output.Point;
import ai.djl.modality.cv.output.Rectangle;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDArrays;
import ai.djl.ndarray.NDList;
import ai.djl.ndarray.NDManager;
import ai.djl.ndarray.types.DataType;
import ai.djl.ndarray.types.Shape;
import ai.djl.translate.Batchifier;
import ai.djl.translate.Translator;
import ai.djl.translate.TranslatorContext;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
```

**MY CODE**

```
Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("https://resources.djl.ai/test-models/pytorch/retinaface.zip")
                        // Load model from local file, e.g:
                        .optModelName("retinaface") // specify model file prefix
                        .optTranslator(translator)
                        .optProgress(new ProgressBar())
                        .optEngine("PyTorch") // Use PyTorch engine
                        .build();
        Image img = ImageFactory.getInstance().fromUrl("https://eskipaper.com/images/face-hd-1.jpg");
        ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria) {
          Predictor<Image, DetectedObjects> predictor = model.newPredictor() {
                DetectedObjects detection = predictor.predict(img);
                img.drawBoundingBoxes(detection);
               var det= detection;

```

I Ignore Translator code because its too long and i m guessing its unneccesary too ..i just wanted to keep this issue clean and simple..

**HERES THE ERROR POPING UP**
`java.lang.NoClassDefFoundError: Could not initialize class ai.djl.repository.zoo.DefaultModelZoo
at ai.djl.repository.zoo.Criteria$Builder.optModelUrls(Criteria.java:390)
	at .(#85:4)`

whats i m missing ...???..please guide me

**Comment by lanking520** [comment]
@nikkisingh111333 0.10.0 only works with PyTorch 1.7.1, so that means you need to make the folloowing changes:

```
%maven ai.djl.pytorch:pytorch-native-auto:1.8.1
```

to

```
%maven ai.djl.pytorch:pytorch-native-auto:1.7.1
```

Apart from that, please remove the following packages to avoid modelzoo initialization conflict:

```
%maven ai.djl:model-zoo:0.10.0
%maven ai.djl:examples:0.6.0
```

**Comment by frankfliu** [comment]
I updated pytorch document, see: https://github.com/deepjavalibrary/djl/tree/master/pytorch/pytorch-engine#installation

**Comment by nikkisingh111333** [comment]
Thanks! i m goona check it out then i ll report you immediately..

**Comment by nikkisingh111333** [comment]
thanks   it workedd.......??????
